// Déclaration des entités football pour l'admin générique (EntityManager).
export const FOOTBALL_ENTITIES = {
  competitions: {
    table: "competitions", title: "Compétitions", singular: "Compétition", orderBy: "position", hasSource: true, slugFrom: "name",
    fields: [
      { key: "name", label: "Nom", type: "text" },
      { key: "position", label: "Ordre (0 = en premier)", type: "number" },
      { key: "slug", label: "Slug (auto si vide)", type: "text" },
      { key: "provider", label: "Provider (ex. thesportsdb)", type: "text" },
      { key: "external_id", label: "ID ligue chez le provider", type: "text" },
      { key: "logo_url", label: "Logo", type: "image" },
      { key: "banner_url", label: "Bannière de la page compétition", type: "image" },
      { key: "header_title", label: "Titre du bandeau (vide = nom)", type: "text" },
      { key: "header_subtitle", label: "Sous-titre du bandeau (vide = pays · saison)", type: "text" },
      { key: "portal_background_url", label: "Portail : fond de la porte (vide = bannière)", type: "image" },
      { key: "portal_border_color", label: "Portail : couleur du contour", type: "color" },
      { key: "portal_overlay", label: "Portail : assombrissement (0 à 1)", type: "number" },
      { key: "portal_title", label: "Portail : titre (vide = titre du bandeau)", type: "text" },
      { key: "portal_subtitle", label: "Portail : texte (vide = sous-titre du bandeau)", type: "textarea" },
      { key: "public_visible", label: "Visible dans les pages publiques", type: "bool" },
      { key: "zones", label: "Zones de classement", type: "zones" },
      { key: "rating_min", label: "Note : min. apparitions", type: "number" },
      { key: "live_enabled", label: "Direct activé pour les jobs automatiques", type: "bool" },
      { key: "live_refresh_seconds", label: "Direct : intervalle conseillé en secondes (30 à 900)", type: "number" },
      { key: "competition_type", label: "Type", type: "select", options: ["league", "cup"] },
    ],
  },
  seasons: {
    table: "seasons", title: "Saisons", singular: "Saison", orderBy: "label",
    fields: [
      { key: "competition_id", label: "Compétition", type: "relation", table: "competitions", labelCol: "name" },
      { key: "label", label: "Libellé (ex. 2026-2027)", type: "text" },
      { key: "zones_by_phase", label: "Zones par phase", type: "phaseZones" },
    ],
  },
  clubs: {
    table: "clubs", title: "Clubs", singular: "Club", orderBy: "name", hasSource: true, search: true,
    fields: [
      { key: "name", label: "Nom", type: "text" },
      { key: "short_name", label: "Abréviation", type: "text" },
      { key: "city", label: "Ville", type: "text" },
      { key: "logo_url", label: "Logo", type: "image" },
      { key: "nickname", label: "Surnom", type: "text" },
      { key: "founded_year", label: "Année de fondation", type: "number" },
      { key: "description", label: "Présentation du club", type: "textarea" },
      { key: "website_url", label: "Site officiel", type: "text" },
      { key: "primary_color", label: "Couleur principale (hex)", type: "color" },
      { key: "secondary_color", label: "Couleur secondaire (hex)", type: "color" },
      { key: "stadium_name", label: "Nom du stade", type: "text" },
      { key: "stadium_capacity", label: "Capacité du stade", type: "number" },
      { key: "stadium_address", label: "Adresse du stade", type: "text" },
      { key: "stadium_image_url", label: "Photo du stade", type: "image" },
      { key: "honours", label: "Palmarès", type: "honours" },
      { key: "team_type", label: "Type d'équipe", type: "select", options: ["first_team", "reserve", "u23", "youth", "women", "national"] },
      { key: "national_category", label: "Catégorie de sélection", type: "select", options: ["senior", "u23", "u21", "u20", "u19", "u18", "u17", "women"] },
      { key: "national_gender", label: "Genre de la sélection", type: "select", options: ["men", "women"] },
      { key: "parent_club_id", label: "Club parent (réserve/U23)", type: "relation", table: "clubs", labelCol: "name" },
    ],
  },
  nationalCallups: {
    table: "national_team_callups", title: "Convocations en sélection", singular: "Convocation", orderBy: "updated_at", orderAsc: false, hasSource: true, pageSize: 40,
    fields: [
      { key: "national_team_id", label: "Sélection", type: "relation", table: "clubs", labelCol: "name" },
      { key: "player_id", label: "Joueur", type: "relation", table: "players", labelCol: "name" },
      { key: "season", label: "Saison", type: "text" },
      { key: "shirt_number", label: "Numéro", type: "number" },
      { key: "position", label: "Poste", type: "text" },
      { key: "active", label: "Dans la sélection actuelle", type: "bool" },
    ],
  },
  players: {
    table: "players", title: "Joueurs", singular: "Joueur", orderBy: "name", hasSource: true, search: true,
    pageSize: 40, grouped: false, groupBy: { field: "club_id", relTable: "clubs", relLabel: "name" },
    quickFilters: [
      { key: "active", label: "Tous les statuts", type: "bool", options: [{ value: "true", label: "Actifs" }, { value: "false", label: "Inactifs" }] },
      { key: "tracked", label: "Tous les suivis", type: "bool", options: [{ value: "true", label: "Suivis Belfoot" }, { value: "false", label: "Non suivis" }] },
    ],
    fields: [
      { key: "name", label: "Nom", type: "text" },
      { key: "club_id", label: "Club actuel", type: "relation", table: "clubs", labelCol: "name" },
      { key: "position", label: "Poste", type: "select", options: ["Goalkeeper", "Defender", "Midfielder", "Attacker", "GK", "DEF", "MID", "FWD"] },
      { key: "number", label: "N°", type: "number" },
      { key: "age", label: "Âge", type: "number" },
      { key: "nationality", label: "Nationalité", type: "text" },
      { key: "country", label: "Pays du championnat", type: "text" },
      { key: "competition", label: "Championnat", type: "text" },
      { key: "photo_url", label: "Photo", type: "image" },
      { key: "active", label: "Actif", type: "bool" },
      { key: "tracked", label: "Suivi Belfoot", type: "bool" },
    ],
  },
  playerMemberships: {
    table: "player_team_seasons", title: "Affectations joueurs", singular: "Affectation", orderBy: "season_start_year", orderAsc: false, hasSource: true, search: false, pageSize: 40, scopeField: "player_id",
    fields: [
      { key: "player_id", label: "Joueur", type: "relation", table: "players", labelCol: "name" },
      { key: "club_id", label: "Club / équipe", type: "relation", table: "clubs", labelCol: "name" },
      { key: "season", label: "Saison (ex. 2024 ou 2024-2025)", type: "text" },
      { key: "season_start_year", label: "Année de début", type: "number" },
      { key: "squad_role", label: "Groupe", type: "select", options: ["first_team", "reserve", "u23", "youth", "women", "unknown"] },
      { key: "membership_type", label: "Type d'affectation", type: "select", options: ["registered", "permanent", "loan", "youth", "reserve", "trial", "legacy"] },
      { key: "position", label: "Poste dans ce groupe", type: "select", options: ["Goalkeeper", "Defender", "Midfielder", "Attacker", "GK", "DEF", "MID", "FWD"] },
      { key: "shirt_number", label: "Numéro", type: "number" },
      { key: "joined_at", label: "Arrivée", type: "date" },
      { key: "left_at", label: "Départ", type: "date" },
      { key: "is_primary", label: "Affectation principale", type: "bool" },
      { key: "active", label: "Visible dans l'effectif de cette saison", type: "bool" },
    ],
  },
  playerCareerStats: {
    table: "player_season_stats", title: "Statistiques de carrière", singular: "Ligne de statistiques", orderBy: "season", orderAsc: false, hasSource: true, pageSize: 40, scopeField: "player_id",
    fields: [
      { key: "player_id", label: "Joueur", type: "relation", table: "players", labelCol: "name" },
      { key: "club_id", label: "Club représenté", type: "relation", table: "clubs", labelCol: "name" },
      { key: "competition_id", label: "Compétition", type: "relation", table: "competitions", labelCol: "name" },
      { key: "season_id", label: "Saison Belfoot", type: "relation", table: "seasons", labelCol: "label" },
      { key: "season", label: "Année provider", type: "text" },
      { key: "appearances", label: "Apparitions", type: "number" },
      { key: "lineups", label: "Titularisations", type: "number" },
      { key: "minutes", label: "Minutes", type: "number" },
      { key: "goals", label: "Buts", type: "number" },
      { key: "assists", label: "Passes décisives", type: "number" },
      { key: "yellow", label: "Cartons jaunes", type: "number" },
      { key: "red", label: "Cartons rouges", type: "number" },
      { key: "rating", label: "Note", type: "number" },
    ],
  },
  coaches: {
    table: "coaches", title: "Entraîneurs", singular: "Entraîneur", orderBy: "name", hasSource: true,
    fields: [
      { key: "name", label: "Nom", type: "text" },
      { key: "club_id", label: "Club", type: "relation", table: "clubs", labelCol: "name" },
      { key: "photo_url", label: "Photo", type: "image" },
      { key: "locked", label: "Protéger des synchronisations", type: "bool" },
    ],
  },
  matches: {
    table: "matches", title: "Matchs", singular: "Match", orderBy: "kickoff", orderAsc: false, hasSource: true, pageSize: 40,
    fields: [
      { key: "competition_id", label: "Compétition", type: "relation", table: "competitions", labelCol: "name" },
      { key: "season_id", label: "Saison", type: "relation", table: "seasons", labelCol: "label" },
      { key: "matchday", label: "Journée", type: "number" },
      { key: "home_club_id", label: "Domicile", type: "relation", table: "clubs", labelCol: "name" },
      { key: "away_club_id", label: "Extérieur", type: "relation", table: "clubs", labelCol: "name" },
      { key: "home_score", label: "Score domicile", type: "number" },
      { key: "away_score", label: "Score extérieur", type: "number" },
      { key: "status", label: "Statut", type: "select", options: ["scheduled", "live", "finished", "postponed"] },
      { key: "minute", label: "Minute", type: "number" },
      { key: "kickoff", label: "Coup d'envoi", type: "datetime" },
    ],
  },
  events: {
    table: "match_events", title: "Événements de match", singular: "Événement", orderBy: "minute", orderAsc: true, pageSize: 40,
    fields: [
      { key: "match_id", label: "Match", type: "relation", table: "matches", labelCol: "id" },
      { key: "minute", label: "Minute", type: "number" },
      { key: "type", label: "Type", type: "select", options: ["goal", "assist", "yellow", "red", "sub"] },
      { key: "player_id", label: "Joueur", type: "relation", table: "players", labelCol: "name" },
      { key: "club_id", label: "Club", type: "relation", table: "clubs", labelCol: "name" },
    ],
  },
  lineups: {
    table: "match_lineups", title: "Formations par match", singular: "Formation", orderBy: "synced_at", orderAsc: false, hasSource: true, pageSize: 40,
    fields: [
      { key: "match_id", label: "Match", type: "relation", table: "matches", labelCol: "id" },
      { key: "competition_id", label: "Compétition", type: "relation", table: "competitions", labelCol: "name" },
      { key: "club_id", label: "Club", type: "relation", table: "clubs", labelCol: "name" },
      { key: "formation", label: "Formation (ex. 4-3-3)", type: "text" },
    ],
  },
  matchPlayerStats: {
    table: "match_player_stats", title: "Compositions et performances", singular: "Joueur du match", orderBy: "synced_at", orderAsc: false, hasSource: true, pageSize: 40,
    fields: [
      { key: "match_id", label: "Match", type: "relation", table: "matches", labelCol: "id" },
      { key: "competition_id", label: "Compétition", type: "relation", table: "competitions", labelCol: "name" },
      { key: "club_id", label: "Club", type: "relation", table: "clubs", labelCol: "name" },
      { key: "player_id", label: "Joueur Belfoot", type: "relation", table: "players", labelCol: "name" },
      { key: "player_external_id", label: "ID joueur provider", type: "text" },
      { key: "player_name", label: "Nom affiché", type: "text" },
      { key: "number", label: "Numéro", type: "number" },
      { key: "position", label: "Poste", type: "text" },
      { key: "grid", label: "Position sur le terrain", type: "text" },
      { key: "starter", label: "Titulaire", type: "bool" },
      { key: "substitute", label: "Remplaçant", type: "bool" },
      { key: "captain", label: "Capitaine", type: "bool" },
      { key: "minutes", label: "Minutes", type: "number" },
      { key: "rating", label: "Note", type: "number" },
      { key: "goals", label: "Buts", type: "number" },
      { key: "assists", label: "Passes décisives", type: "number" },
      { key: "saves", label: "Arrêts", type: "number" },
      { key: "goals_conceded", label: "Buts encaissés", type: "number" },
      { key: "yellow", label: "Cartons jaunes", type: "number" },
      { key: "red", label: "Cartons rouges", type: "number" },
    ],
  },
};
