// Déclaration des entités football pour l'admin générique (EntityManager).
export const FOOTBALL_ENTITIES = {
  competitions: {
    table: "competitions", title: "Compétitions", singular: "Compétition", orderBy: "position", hasSource: true, slugFrom: "name",
    fields: [
      { key: "name", label: "Nom", type: "text" },
      { key: "position", label: "Ordre (0 = en premier)", type: "number" },
      { key: "slug", label: "Slug (auto si vide)", type: "text" },
      { key: "provider", label: "Provider (ex. thesportsdb)", type: "text" },
      { key: "external_id", label: "ID ligue chez le provider", type: "text" },
      { key: "logo_url", label: "Logo", type: "image" },
      { key: "banner_url", label: "Bannière de la page compétition", type: "image" },
      { key: "header_title", label: "Titre du bandeau (vide = nom)", type: "text" },
      { key: "header_subtitle", label: "Sous-titre du bandeau (vide = pays · saison)", type: "text" },
      { key: "portal_background_url", label: "Portail : fond de la porte (vide = bannière)", type: "image" },
      { key: "portal_border_color", label: "Portail : couleur du contour", type: "color" },
      { key: "portal_overlay", label: "Portail : assombrissement (0 à 1)", type: "number" },
      { key: "portal_title", label: "Portail : titre (vide = titre du bandeau)", type: "text" },
      { key: "portal_subtitle", label: "Portail : texte (vide = sous-titre du bandeau)", type: "textarea" },
      { key: "public_visible", label: "Visible dans les pages publiques", type: "bool" },
      { key: "zones", label: "Zones de classement", type: "zones" },
      { key: "rating_min", label: "Note : min. apparitions", type: "number" },
      { key: "competition_type", label: "Type", type: "select", options: ["league", "cup"] },
    ],
  },
  seasons: {
    table: "seasons", title: "Saisons", singular: "Saison", orderBy: "label",
    fields: [
      { key: "competition_id", label: "Compétition", type: "relation", table: "competitions", labelCol: "name" },
      { key: "label", label: "Libellé (ex. 2026-2027)", type: "text" },
      { key: "zones_by_phase", label: "Zones par phase", type: "phaseZones" },
    ],
  },
  clubs: {
    table: "clubs", title: "Clubs", singular: "Club", orderBy: "name", hasSource: true, search: true,
    fields: [
      { key: "name", label: "Nom", type: "text" },
      { key: "short_name", label: "Abréviation", type: "text" },
      { key: "city", label: "Ville", type: "text" },
      { key: "logo_url", label: "Logo", type: "image" },
      { key: "nickname", label: "Surnom", type: "text" },
      { key: "founded_year", label: "Année de fondation", type: "number" },
      { key: "description", label: "Présentation du club", type: "textarea" },
      { key: "website_url", label: "Site officiel", type: "text" },
      { key: "primary_color", label: "Couleur principale (hex)", type: "color" },
      { key: "secondary_color", label: "Couleur secondaire (hex)", type: "color" },
      { key: "stadium_name", label: "Nom du stade", type: "text" },
      { key: "stadium_capacity", label: "Capacité du stade", type: "number" },
      { key: "stadium_address", label: "Adresse du stade", type: "text" },
      { key: "stadium_image_url", label: "Photo du stade", type: "image" },
      { key: "honours", label: "Palmarès", type: "honours" },
      { key: "team_type", label: "Type d'équipe", type: "select", options: ["first_team", "reserve", "u23", "women"] },
      { key: "parent_club_id", label: "Club parent (réserve/U23)", type: "relation", table: "clubs", labelCol: "name" },
    ],
  },
  players: {
    table: "players", title: "Joueurs", singular: "Joueur", orderBy: "name", hasSource: true, search: true, groupBy: { field: "club_id", relTable: "clubs", relLabel: "name" },
    fields: [
      { key: "name", label: "Nom", type: "text" },
      { key: "club_id", label: "Club actuel", type: "relation", table: "clubs", labelCol: "name" },
      { key: "position", label: "Poste", type: "select", options: ["GK", "DEF", "MID", "FWD"] },
      { key: "number", label: "N°", type: "number" },
      { key: "age", label: "Âge", type: "number" },
      { key: "nationality", label: "Nationalité", type: "text" },
      { key: "country", label: "Pays du championnat", type: "text" },
      { key: "competition", label: "Championnat", type: "text" },
      { key: "photo_url", label: "Photo", type: "image" },
      { key: "active", label: "Actif", type: "bool" },
      { key: "tracked", label: "Suivi Belfoot", type: "bool" },
    ],
  },
  coaches: {
    table: "coaches", title: "Entraîneurs", singular: "Entraîneur", orderBy: "name", hasSource: true,
    fields: [
      { key: "name", label: "Nom", type: "text" },
      { key: "club_id", label: "Club", type: "relation", table: "clubs", labelCol: "name" },
      { key: "photo_url", label: "Photo", type: "image" },
      { key: "locked", label: "Protéger des synchronisations", type: "bool" },
    ],
  },
  matches: {
    table: "matches", title: "Matchs", singular: "Match", orderBy: "kickoff", orderAsc: false, hasSource: true,
    fields: [
      { key: "competition_id", label: "Compétition", type: "relation", table: "competitions", labelCol: "name" },
      { key: "season_id", label: "Saison", type: "relation", table: "seasons", labelCol: "label" },
      { key: "matchday", label: "Journée", type: "number" },
      { key: "home_club_id", label: "Domicile", type: "relation", table: "clubs", labelCol: "name" },
      { key: "away_club_id", label: "Extérieur", type: "relation", table: "clubs", labelCol: "name" },
      { key: "home_score", label: "Score domicile", type: "number" },
      { key: "away_score", label: "Score extérieur", type: "number" },
      { key: "status", label: "Statut", type: "select", options: ["scheduled", "live", "finished", "postponed"] },
      { key: "minute", label: "Minute", type: "number" },
      { key: "kickoff", label: "Coup d'envoi", type: "datetime" },
    ],
  },
  events: {
    table: "match_events", title: "Événements de match", singular: "Événement", orderBy: "minute", orderAsc: true,
    fields: [
      { key: "match_id", label: "Match", type: "relation", table: "matches", labelCol: "id" },
      { key: "minute", label: "Minute", type: "number" },
      { key: "type", label: "Type", type: "select", options: ["goal", "assist", "yellow", "red", "sub"] },
      { key: "player_id", label: "Joueur", type: "relation", table: "players", labelCol: "name" },
      { key: "club_id", label: "Club", type: "relation", table: "clubs", labelCol: "name" },
    ],
  },
  lineups: {
    table: "match_lineups", title: "Formations par match", singular: "Formation", orderBy: "synced_at", orderAsc: false, hasSource: true,
    fields: [
      { key: "match_id", label: "Match", type: "relation", table: "matches", labelCol: "id" },
      { key: "competition_id", label: "Compétition", type: "relation", table: "competitions", labelCol: "name" },
      { key: "club_id", label: "Club", type: "relation", table: "clubs", labelCol: "name" },
      { key: "formation", label: "Formation (ex. 4-3-3)", type: "text" },
    ],
  },
  matchPlayerStats: {
    table: "match_player_stats", title: "Compositions et performances", singular: "Joueur du match", orderBy: "synced_at", orderAsc: false, hasSource: true,
    fields: [
      { key: "match_id", label: "Match", type: "relation", table: "matches", labelCol: "id" },
      { key: "competition_id", label: "Compétition", type: "relation", table: "competitions", labelCol: "name" },
      { key: "club_id", label: "Club", type: "relation", table: "clubs", labelCol: "name" },
      { key: "player_id", label: "Joueur Belfoot", type: "relation", table: "players", labelCol: "name" },
      { key: "player_external_id", label: "ID joueur provider", type: "text" },
      { key: "player_name", label: "Nom affiché", type: "text" },
      { key: "number", label: "Numéro", type: "number" },
      { key: "position", label: "Poste", type: "text" },
      { key: "grid", label: "Position sur le terrain", type: "text" },
      { key: "starter", label: "Titulaire", type: "bool" },
      { key: "substitute", label: "Remplaçant", type: "bool" },
      { key: "captain", label: "Capitaine", type: "bool" },
      { key: "minutes", label: "Minutes", type: "number" },
      { key: "rating", label: "Note", type: "number" },
      { key: "goals", label: "Buts", type: "number" },
      { key: "assists", label: "Passes décisives", type: "number" },
      { key: "saves", label: "Arrêts", type: "number" },
      { key: "goals_conceded", label: "Buts encaissés", type: "number" },
      { key: "yellow", label: "Cartons jaunes", type: "number" },
      { key: "red", label: "Cartons rouges", type: "number" },
    ],
  },
};
